export enum DamageType {
    ACID = "ac",
    COLD = "co",
    FIRE = "fi",
    FORCE = "fo",
    LIGHTNING = "li",
    NECROTIC = "ne",
    POISON = "po",
    PSYCHIC = "ps",
    RADIANT = "ra",
    THUNDER = "th",
    PIERCING = "pi",
    SLASHING = "sl",
    BLUDGEONING = "bl",
    M_PIERCING = "mp",
    M_SLASHING = "ms",
    M_BLUDGEONING = "mb",
}