export enum DamageType {
    ACID = "acid",
    COLD = "cold",
    FIRE = "fire",
    FORCE = "force",
    LIGHTNING = "lighting",
    NECROTIC = "necrotic",
    POISON = "poison",
    PSYCHIC = "psychic",
    RADIANT = "radiant",
    THUNDER = "thunder",
    PIERCING = "piercing",
    SLASHING = "slashing",
    BLUDGEONING = "bludgeoning",
    M_PIERCING = "mpiercing",
    M_SLASHING = "mslinging",
    M_BLUDGEONING = "mbludgeoning",
}