version: "3.8"
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: .
    container_name: dnd-backend
    command: npm run dev
    working_dir: /usr/src/app
    volumes:
      - ./src:/usr/src/app/src
      - /usr/src/app/node_modules
      - ./package.json:/usr/src/app/package.json
      - ./tsconfig.json:/usr/src/app/tsconfig.json
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/dndapp
    depends_on:
      - mongo

volumes:
  mongo_data:
